# -*- coding: utf-8 -*-
"""DT_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNpfRt0vIoXWnS24q7ktWEkQ74_aXAOP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.tree import export_text

import warnings
warnings.filterwarnings("ignore")

print("✅ All libraries imported successfully.")

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))

print("=" * 55)
print("DATASET INFO")
print("=" * 55)
df.info()

print("\n" + "=" * 55)
print("MISSING VALUES")
print("=" * 55)
print(df.isnull().sum())

print("\n" + "=" * 55)
print("CLASS DISTRIBUTION  (Target: behavioural_label)")
print("=" * 55)
print(df["behavioural_label"].value_counts())

# Plot class distribution
fig, ax = plt.subplots(figsize=(9, 4))
df["behavioural_label"].value_counts().plot(
    kind="bar", ax=ax, color="steelblue", edgecolor="black"
)
ax.set_title("Class Distribution — behavioural_label", fontsize=14)
ax.set_xlabel("Class")
ax.set_ylabel("Count")
ax.tick_params(axis="x", rotation=30)
plt.tight_layout()
plt.show()

print("\n" + "=" * 55)
print("FEATURE STATISTICS")
print("=" * 55)
print(df.describe())

# ── Drop non-numeric / ID columns ──
DROP_COLS = ["attempt_id", "assessment_id", "subject"]
df_model = df.drop(columns=DROP_COLS, errors="ignore").copy()

# ── Encode target label ──
le = LabelEncoder()
df_model["label_encoded"] = le.fit_transform(df_model["behavioural_label"])

print("📌 Class → Encoded Mapping:")
for cls, enc in zip(le.classes_, le.transform(le.classes_)):
    print(f"   {enc}  →  {cls}")

# ── Define features and target ──
FEATURE_COLS = [
    "avg_time", "time_variance", "revision_count",
    "wr_ratio", "rw_ratio", "navigation_count",
    "rte_score", "accuracy"
]

X = df_model[FEATURE_COLS]
y = df_model["label_encoded"]

print(f"\n✅ Features : {FEATURE_COLS}")
print(f"✅ Target   : 'behavioural_label' (encoded)")
print(f"✅ X shape  : {X.shape}  |  y shape: {y.shape}")

# ── Feature correlation heatmap ──
fig, ax = plt.subplots(figsize=(9, 7))
corr = X.corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
            linewidths=0.5, ax=ax)
ax.set_title("Feature Correlation Heatmap", fontsize=14)
plt.tight_layout()
plt.show()

# Stratified split preserves class proportions in both sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,       # 80% train · 20% test
    random_state=42,
    stratify=y            # IMPORTANT: keeps class balance
)

print(f"✅ Train size : {X_train.shape[0]} samples")

print(f"✅ Test  size : {X_test.shape[0]} samples")

print("\n📊 Class distribution in TRAIN set:")
train_dist = pd.Series(y_train).map(
    dict(enumerate(le.classes_))
).value_counts()
print(train_dist)

print("\n📊 Class distribution in TEST set:")
test_dist = pd.Series(y_test).map(
    dict(enumerate(le.classes_))
).value_counts()
print(test_dist)

from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth"        : [3, 4, 5, 6, 7, 8, None],
    "min_samples_leaf" : [1, 2, 3, 5, 8, 10],
    "criterion"        : ["gini", "entropy"],
    "class_weight"     : [None, "balanced"],   # handles class imbalance
}

base_clf = DecisionTreeClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator  = base_clf,
    param_grid = param_grid,
    cv         = StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
    scoring    = "accuracy",
    n_jobs     = -1,
    verbose    = 1
)

print("🔍 Running GridSearchCV — this may take a few seconds...")
grid_search.fit(X_train, y_train)

print(f"\n✅ Best Parameters  : {grid_search.best_params_}")
print(f"✅ Best CV Accuracy : {grid_search.best_score_:.4f}")

best_clf = grid_search.best_estimator_

# Re-fit on full training set (GridSearchCV already does this,
# but we call it explicitly for clarity)
best_clf.fit(X_train, y_train)

print("✅ Best Decision Tree trained on training set.")
print(f"   Tree depth      : {best_clf.get_depth()}")
print(f"   Number of leaves: {best_clf.get_n_leaves()}")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(best_clf, X, y, cv=cv, scoring="accuracy")

print("=" * 55)
print("5-FOLD STRATIFIED CROSS-VALIDATION RESULTS")
print("=" * 55)
for i, score in enumerate(cv_scores, 1):
    print(f"  Fold {i}: {score:.4f}")
print(f"\n  Mean Accuracy : {cv_scores.mean():.4f}")
print(f"  Std Deviation : {cv_scores.std():.4f}")
print(f"  95% CI        : [{cv_scores.mean() - 2*cv_scores.std():.4f}"
      f", {cv_scores.mean() + 2*cv_scores.std():.4f}]")

# Plot CV scores
fig, ax = plt.subplots(figsize=(7, 4))
ax.bar(range(1, 6), cv_scores, color="teal", edgecolor="black", alpha=0.8)
ax.axhline(cv_scores.mean(), color="red", linestyle="--",
           label=f"Mean = {cv_scores.mean():.4f}")
ax.set_title("Cross-Validation Accuracy per Fold", fontsize=13)
ax.set_xlabel("Fold")
ax.set_ylabel("Accuracy")
ax.set_ylim(0, 1.05)
ax.legend()
plt.tight_layout()
plt.show()

y_pred = best_clf.predict(X_test)

test_accuracy = accuracy_score(y_test, y_pred)

print("=" * 55)
print("TEST SET EVALUATION")
print("=" * 55)
print(f"\n🎯 Test Accuracy : {test_accuracy:.4f}  ({test_accuracy*100:.2f}%)")

print("\n📋 Classification Report:")
print(classification_report(
    y_test, y_pred,
    target_names=le.classes_
))

sanity_samples = pd.DataFrame({
    #                    Dis    HighRev  Review  FastR   Delib   Incon
    "avg_time"         : [4.5,   24.0,   24.0,   8.9,   32.0,   22.0],
    "time_variance"    : [1.8,   183.0,  195.0,  3.8,   117.0,  436.0],
    "revision_count"   : [0.7,   9.0,    4.8,    1.4,   3.3,    2.3  ],
    "wr_ratio"         : [0.03,  0.32,   0.22,   0.07,  0.16,   0.31 ],
    "rw_ratio"         : [0.06,  0.61,   0.59,   0.13,  0.48,   0.37 ],
    "navigation_count" : [1.3,   10.9,   8.6,    2.4,   4.7,    4.6  ],
    "rte_score"        : [0.24,  1.44,   1.38,   0.67,  2.70,   1.15 ],
    "accuracy"         : [0.17,  0.57,   0.64,   0.79,  0.71,   0.55 ],
})

expected = ["Disengaged", "High-Revision", "Reviewer",
            "Fast-Response", "Deliberative", "Inconsistent"]

preds = le.inverse_transform(best_clf.predict(sanity_samples))

print(f"{'Expected':<20} {'Predicted':<20} {'Match'}")
print("-" * 50)
for exp, pred in zip(expected, preds):
    match = "✅" if exp == pred else "❌ WRONG"
    print(f"{exp:<20} {pred:<20} {match}")

# class_means = df.groupby("behavioural_label")[FEATURE_COLS].mean().round(3)
# preds = le.inverse_transform(best_clf.predict(class_means))
# expected = list(class_means.index)

# for exp, pred in zip(expected, preds):
#     print(f"{exp:<20} {pred:<20} {'✅' if exp == pred else '❌'}")

# ============================================================
# BLOCK 10 — Sanity Test (Data-Driven)
# ============================================================

# Step 1 — See actual class means
class_means = df.groupby("behavioural_label")[FEATURE_COLS].mean().round(3)
print("📊 Actual Class Means:")
print(class_means)

# Step 2 — Test with real class means (guaranteed valid inputs)
preds = le.inverse_transform(best_clf.predict(class_means))
expected = list(class_means.index)

print(f"\n{'Expected':<20} {'Predicted':<20} {'Match'}")
print("-" * 50)
for exp, pred in zip(expected, preds):
    match = "✅" if exp == pred else "❌ WRONG"
    print(f"{exp:<20} {pred:<20} {match}")

# Step 3 — Confidence per prediction
proba = best_clf.predict_proba(class_means)
confidence = proba.max(axis=1) * 100

print(f"\n{'Class':<20} {'Confidence'}")
print("-" * 35)
for cls, conf in zip(expected, confidence):
    flag = "✅" if conf >= 80 else "⚠️  LOW"
    print(f"{cls:<20} {conf:.1f}%  {flag}")

fig, ax = plt.subplots(figsize=(40, 15))
plot_tree(
    best_clf,                        # ← correct variable name (not 'model')
    feature_names = FEATURE_COLS,    # ← use FEATURE_COLS (not X.columns)
    class_names   = le.classes_,     # ← use le.classes_ (not True)
    filled        = True,
    rounded       = True,
    fontsize      = 8,
    ax            = ax
)
plt.title("Decision Tree — depth 7", fontsize=16)
plt.tight_layout()
plt.savefig("decision_tree.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved as decision_tree.png")

